INSERT INTO restaurant.MENU (ID, IS_DELETED, LOCKING_KEY, CREATED_ON, RESTAURANT_ID) VALUES (2, 'N', 0, '2015-11-23', 2);
INSERT INTO restaurant.MENU (ID, IS_DELETED, LOCKING_KEY, CREATED_ON, RESTAURANT_ID) VALUES (3, 'N', 0, '2015-11-23', 3);
INSERT INTO restaurant.MENU (ID, IS_DELETED, LOCKING_KEY, CREATED_ON, RESTAURANT_ID) VALUES (4, 'N', 0, '2015-11-23', 4);
INSERT INTO restaurant.MENU (ID, IS_DELETED, LOCKING_KEY, CREATED_ON, RESTAURANT_ID) VALUES (5, 'N', 0, '2015-11-23', 5);
INSERT INTO restaurant.MENU (ID, IS_DELETED, LOCKING_KEY, CREATED_ON, RESTAURANT_ID) VALUES (6, 'N', 0, '2015-11-21', 2);
