INSERT INTO restaurant.RESTAURANT (ID, IS_DELETED, LOCKING_KEY, NAME) VALUES (2, 'N', 0, 'Il-tokio');
INSERT INTO restaurant.RESTAURANT (ID, IS_DELETED, LOCKING_KEY, NAME) VALUES (3, 'N', 0, 'Tanuki');
INSERT INTO restaurant.RESTAURANT (ID, IS_DELETED, LOCKING_KEY, NAME) VALUES (4, 'N', 0, 'Gvozdy');
INSERT INTO restaurant.RESTAURANT (ID, IS_DELETED, LOCKING_KEY, NAME) VALUES (5, 'N', 0, 'O''Hara');
