INSERT INTO restaurant.USER_ROLE (USER_ID, ROLE_ID) VALUES (2, 2);
INSERT INTO restaurant.USER_ROLE (USER_ID, ROLE_ID) VALUES (3, 3);
INSERT INTO restaurant.USER_ROLE (USER_ID, ROLE_ID) VALUES (4, 3);
